# Generated by Django 6.1.1 on 2026-09-08 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='review_text',
            field=models.TextField(blank=True, default=''),
        ),
    ]
