# Generated by Django 5.2.8 on 2026-09-08 08:39

import cloudinary.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_alter_order_status'),
        ('products', '0007_productrating_review_text'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.PositiveSmallIntegerField()),
                ('performance_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('battery_life_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('product_quality_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('condition_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('value_for_money_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('design_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('features_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('size_fit_rating', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('review_text', models.TextField(blank=True, default='')),
                ('verified_purchase', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('published', 'Published'), ('hidden', 'Hidden')], default='published', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='product_reviews', to='orders.order')),
                ('order_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='review', to='orders.orderitem')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ReviewImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('review', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.productreview')),
            ],
        ),
        migrations.DeleteModel(
            name='ProductRating',
        ),
        migrations.AddConstraint(
            model_name='productreview',
            constraint=models.UniqueConstraint(fields=('product', 'user', 'order'), name='unique_product_user_order_review'),
        ),
    ]
