# Generated by Django 5.2.8 on 2026-09-09 15:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_productreview_reviewimage_delete_productrating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='uuid',
                field=models.UUIDField(null=True, editable=False),
        ),
            migrations.RunPython(
                lambda apps, schema_editor: [
                    setattr(category, 'uuid', uuid.uuid4()) or category.save(update_fields=['uuid'])
                    for category in apps.get_model('products', 'Category').objects.all()
                ],
                migrations.RunPython.noop,
            ),
            migrations.AlterField(
                model_name='category',
                name='uuid',
                field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
            ),
    ]
