# Generated by Django 5.2.8 on 2026-09-11 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='district',
            options={'ordering': ['region', 'name']},
        ),
        migrations.AddField(
            model_name='district',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
